[package]
name = "strike-wallet"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
solana-program = "=1.7.11"
thiserror = "1.0.30"
arrayref = "0.3.6"
itertools = "0.10.3"
spl-associated-token-account = "=1.0.3"
spl-token = "=3.2.0"

[features]
test-bpf = []
no-entrypoint = []

[dev-dependencies]
assert_matches = "1.5.0"
grcov = "0.8.4"
solana-program-test = "=1.7.11"
solana-sdk = "=1.7.11"
solana-validator = "=1.7.11"

[lib]
crate-type = ["cdylib", "lib"]
